$(document).ready(function(){
  $("button#light-theme").click(function(){
   $("body").removeClass();
  });
  $("button#dark-theme").click(function(){
    $("body").removeClass();
    $("body").addClass("dark-background");
  });
});
